name: Deploy

inputs:
  env_aws_secret_name:
    required: true
    type: string
  dir:
    required: true
    type: string

runs:
  using: "composite"
  steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        lfs: "true"
        submodules: "recursive"

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"
        cache: "pip"

    - run: pip install -r deploy_requirements.txt
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
        role-session-name: ${{ inputs.role-session-name }}
        aws-region: ${{ inputs.aws-region }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.3.3

    - name: Deploy
      run: |
        ./scripts/deploy.sh ${{ inputs.env-file }} <<< init
        ./scripts/deploy.sh ${{ inputs.env-file }} <<< deploy
