name: CICD 🚀

permissions:
  id-token: write
  contents: read

on:
  push:
    branches:
      - access-analyser

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          lfs: "true"
          submodules: "recursive"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.DEPLOYMENT_ROLE_ARN }}
          role-session-name: "ghgc-airflow-github--deployment"
          aws-region: "us-west-2"

      - name: Run deployment
        uses: "./.github/actions/terraform-deploy"
        with:
          env_aws_secret_name: ${{ secrets.ENV_AWS_SECRET_NAME }}
          env-file: ".env_development"
